# Generated by Django 2.1.dev20180206232904 on 2018-02-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odc1',
            name='id',
        ),
        migrations.AddField(
            model_name='odc1',
            name='person_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
