# Generated by Django 2.1.dev20180206232904 on 2018-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysongs', '0002_auto_20180213_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtable',
            name='user_rating',
            field=models.IntegerField(null=True),
        ),
    ]
