# Generated by Django 2.1.dev20180206232904 on 2018-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysongs', '0003_auto_20180213_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingtable',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
