# Generated by Django 2.1.dev20180206232904 on 2018-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysongs', '0004_ratingtable_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingtable',
            name='view_count',
        ),
        migrations.AddField(
            model_name='songstable',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
